#!/bin/bash
# Install terraform
wget -nv -nc https://releases.hashicorp.com/terraform/0.8.0-beta2/terraform_0.8.0-beta2_linux_amd64.zip
unzip terraform_0.8.0-beta2_linux_amd64.zip
sudo mv terraform /usr/local/bin
rm terraform_0.8.0-beta2_linux_amd64.zip
